apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodata
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  storageClassName: standard
  hostPath:
    path: /data 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongopvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongoconfig
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  storageClassName: standard
  hostPath:
    path: /config 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongoconfigpvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        volumeMounts:
        - mountPath: "/data/db"
          name: mongopvc
        - mountPath: "/data/configdb"
          name: mongoconfigpvc
        ports:
        - containerPort: 27017        
      volumes:
        - name: mongopvc
          persistentVolumeClaim:
            claimName: mongopvc
        - name: mongoconfigpvc
          persistentVolumeClaim:
            claimName: mongoconfigpvc
